version: "3.9"
services:
  permify:
    image: "ghcr.io/permify/permify:v0.5.3"
    command: "serve --database-engine postgres --database-uri postgres://postgres:secret@database:5432/permify --server-rate-limit 200 --database-max-open-connections 100"
    restart: "always"
    ports:
      - "3476:3476"
      - "3478:3478"
    depends_on:
      - "database"

  database:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_DB=permify"

volumes:
  pg-data:
